let Spaces = [
  {
    key: 1,
    name: "Brick Aux",
    description: "A nice small studio",
    url: "https://www.bricktheater.com/rent-brick-aux-studio/",
    neighborhood: "Williamsburg",
    borough: "Brooklyn",
    coordinates: [40.71401, -73.94811],
    modeOfBooking: "Email",
    cost: "Cheap",
    iframe: `
      <iframe
        loading="lazy"
        src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;ctz=America%2FNew_York&amp;bgcolor=%23ffffff&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;mode=WEEK&amp;src=OTU0aGFva2F2OXJmdGtjNnNmOWc3OTFzZzRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%233F51B5"
        width="100%"
        height="600"
        frameborder="0"
        scrolling="no"
      ></iframe>
    `,
  },
  {
    key: 3,
    name: "Triskelion Arts",
    description: "Three studios and a theatre",
    url: "https://www.triskelionarts.org/availability-calendar",
    location: "Greenpoint, Brooklyn",
    neighborhood: "Greenpoint",
    borough: "Brooklyn",
    coordinates: [40.72696, -73.95656],
    modeOfBooking: "Online",
    cost: "Cheap",
    iframe: (
      <>
        <iframe
          src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FNew_York&amp;src=NmdvZ2FzNTdmMG9kZG9uMWVzbnA0bGE3dWNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%230B8043&amp;mode=WEEK"
          width="100%"
          height="600"
          title="calendar-google"
          data-uw-rm-iframe="gn"
        ></iframe>
        <iframe
          src="https://calendar.google.com/calendar/embed?mode=WEEK&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=uceogoama2cd43fj0pojieafas%40group.calendar.google.com&amp;color=%23B1365F&amp;ctz=America%2FNew_York"
          width="100%"
          height="600"
          title="calendar-google"
          data-uw-rm-iframe="gn"
        ></iframe>
        <iframe
          src="https://calendar.google.com/calendar/embed?mode=WEEK&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=dche191t1jdue3ueh0aucfivgg%40group.calendar.google.com&amp;color=%23333333&amp;ctz=America%2FNew_York"
          width="100%"
          height="600"
          title="calendar-google"
          data-uw-rm-iframe="gn"
        ></iframe>
        <iframe
          src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FNew_York&amp;mode=WEEK&amp;src=aWo5cXJxdjNpYm5jcGdodHBndHAyNXIybmdAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%239E69AF"
          width="100%"
          height="600"
          title="calendar-google"
          data-uw-rm-iframe="gn"
        ></iframe>
      </>
    ),
  },
  {
    key: 4,
    name: "Abrons Arts Center",
    description: "A bunch of studios and like three theaters",
    url: "https://abronsartscenter.org/rentals/studio",
    location: "Lower East Side, Manhattan",
    neighborhood: "Lower East Side",
    borough: "Manhattan",
    coordinates: [40.71525, -73.98374],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 5,
    name: "The Tank Attic",
    description: "Three studios",
    url: "https://thetanknyc.org/attic-tank-page",
    location: "Midtown",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.75359, -73.99327],
    modeOfBooking: "Online",
    cost: "Cheap",
  },
  {
    key: 6,
    name: "OTION",
    description: "A studio in a shed in a backyard",
    url: "https://otionfront.com/",
    location: "Bushwick, Brooklyn",
    neighborhood: "Bushwick",
    borough: "Brooklyn",
    coordinates: [40.69723, -73.93094],
    modeOfBooking: "Online",
    cost: "Cheap",
  },
  {
    key: 8,
    url: "https://www.motivebrooklyn.com/studio-rentals",
    name: "MOtiVE",
    description: "Lovely little small studio",
    neighborhood: "DUMBO",
    borough: "Brooklyn",
    coordinates: [40.70264, -73.98719],
    modeOfBooking: "Online",
    cost: "Cheap",
  },
  {
    name: "Center for Performance Research",
    description:
      "Two spaces: a long small studio and a proper white box theatre",
    url: "https://www.cprnyc.org/booking",
    neighborhood: "Williamsburg",
    borough: "Brooklyn",
    key: 9,
    coordinates: [40.71667, -73.9467],
    modeOfBooking: "Email",
    cost: "Cheap",
    iframe: (
      <>
        <iframe
          src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FNew_York&amp;mode=WEEK&amp;src=Y3BybnljLm9yZ19qMGpyc25hMnZuZ245ZGRpb2MwNTUwdjVhMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t&amp;color=%230B8043"
          width="100%"
          height="600"
        ></iframe>
        <iframe
          src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FNew_York&amp;mode=WEEK&amp;src=Y3BybnljLm9yZ19wdWZkZ3ZjYWxrZHIzZ2w0NGUxM3ZuMGRnc0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t&amp;color=%238E24AA"
          width="100%"
          height="600"
          frameborder="0"
          scrolling="no"
        ></iframe>
      </>
    ),
  },
  {
    key: 10,
    name: "Chez Bushwick",
    description: "Loft with 50% windows, great for dance!",
    url: "https://chezbushwick.net/",
    neighborhood: "Bushwick",
    borough: "Brooklyn",
    coordinates: [40.70664, -73.93529],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 11,
    name: "The Woods",
    description: "Never been here!",
    url: "https://www.thewoodsuniverse.com/",
    neighborhood: "Ridgewood",
    borough: "Queens",
    coordinates: [40.70336, -73.90684],
    modeOfBooking: "Online",
    cost: "Cheap",
    iframe: (
      <iframe
        src="https://thewoods.skedda.com/booking?embedded=true"
        width="100%"
        height="600"
      ></iframe>
    ),
  },
  {
    key: 12,
    name: "Green Space Studio",
    description: "Never been here!",
    url: "https://www.greenspacestudio.org/space",
    neighborhood: "Long Island City",
    borough: "Queens",
    coordinates: [40.75677, -73.93627],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 13,
    name: "Playwrights Horizons Downtown",
    description: "",
    url: "https://www.playwrightshorizons.org/about/playwrights-downtown/",
    neighborhood: "Union Square-ea",
    borough: "Manhattan",
    coordinates: [40.7294868, -73.9922345],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 14,
    name: "Open Arts Studio",
    description: "Lovely studio for dance",
    url: "https://www.openartsstudio.org/bookstudio",
    neighborhood: "DUMBO",
    borough: "Brooklyn",
    coordinates: [40.7027571, -73.9868342],
    modeOfBooking: "Online",
    cost: "Cheap",
  },
  {
    key: 15,
    name: "Mark Morris Dance",
    description: "GORGEOUS STUDIOS!!!!!!!!!!!!!!!",
    url: "https://markmorrisdancegroup.org/dance-center/space-rental/",
    neighborhood: "Downtown",
    borough: "Brooklyn",
    coordinates: [40.6869728, -73.9789195],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 16,
    name: "Vangeline",
    description: "Never been!",
    url: "https://www.vangeline.com/space-rental",
    neighborhood: "Gowanus",
    borough: "Brooklyn",
    coordinates: [40.67159, -73.99352],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 17,
    name: "Dancewave",
    description: "Never been!",
    url: "https://dancewave.org/studio-rental/",
    neighborhood: "Gowanus",
    borough: "Brooklyn",
    coordinates: [40.67894, -73.98246],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 18,
    name: "The Floor on Atlantic",
    description: "Never been!",
    url: "https://www.theflooronatlantic.com/rentals",
    neighborhood: "Boerum Hill",
    borough: "Brooklyn",
    coordinates: [40.68814, -73.98862],
    modeOfBooking: "Online",
    cost: "Cheap",
  },
  {
    key: 19,
    name: "Molloy Studios",
    description: "Never been!",
    url: "https://www.molloy.edu/about/campus-facilities/manhattan-center/studios/",
    neighborhood: "FiDi",
    borough: "Manhattan",
    coordinates: [40.70633079868207, -74.01252974684996],
    modeOfBooking: "Phone",
    cost: "Not Cheap",
  },
  {
    key: 20,
    name: "Battery Dance",
    description: "Never been!",
    url: "https://batterydance.org/studios/",
    neighborhood: "Around Canal Street",
    borough: "Manhattan",
    coordinates: [40.71804, -74.0035972],
    modeOfBooking: "Online",
    cost: "Not Cheap",
  },
  {
    key: 21,
    name: "LEIMAY Cave",
    description:
      "According to their website, you can book up to 25 rehearsal hours a year after paying a $35 annual membership fee",
    url: "https://temporary.leimay.org/studio-subsidy/#",
    neighborhood: "Williamsburg",
    borough: "Brooklyn",
    coordinates: [40.7157083, -73.9656916],
    modeOfBooking: "Online",
    cost: "Cheap",
  },
  {
    key: 22,
    name: "Ballet Hispánico",
    description: "Never been!",
    url: "https://ballethispanico.org/studio-rentals",
    neighborhood: "UWS",
    borough: "Manhattan",
    coordinates: [40.78957, -73.9727921],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 23,
    name: "Dance Theatre of Harlem",
    description: "Never been!",
    url: "https://dancetheatreofharlem.org/studio-rentals/",
    neighborhood: "West Harlem",
    borough: "Manhattan",
    coordinates: [40.8291437, -73.9437309],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 24,
    name: "Dancewave",
    description: "Have not booked here before!",
    url: "https://dancewave.org/studio-rental",
    neighborhood: "Gowanus",
    borough: "Brooklyn",
    coordinates: [40.7443464, -74.0074636],
    modeOfBooking: "Online",
    cost: "Cheap",
  },
  {
    key: 25,
    name: "Fourth Arts Block (FABnyc)",
    description: "Have not booked here before",
    url: "http://www.fabnyc.org/programs/studio-space-70/",
    neighborhood: "East Village",
    borough: "Manhattan",
    coordinates: [40.7443464, -74.0074636],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 26,
    name: "Hi-ARTS",
    description: "Have not booked here before",
    url: "https://www.hi-artsnyc.org/space-rentals",
    neighborhood: "Harlem",
    borough: "Manhattan",
    coordinates: [40.7443464, -74.0074636],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 27,
    name: "Movement Research",
    description: "Requests must be sent a minimum of one week in advance",
    url: "https://movementresearch.org/artist-opportunities-and-programs/subsidized-rehearsal-space/",
    neighborhood: "East Village",
    borough: "Manhattan",
    coordinates: [40.7282081, -73.984491],
    modeOfBooking: "Online",
    cost: "Cheap",
  },
  {
    key: 28,
    name: "Mind-Builders Creative Arts Center",
    description: "Have not visited here before",
    url: "https://www.mind-builders.org/contact/space-rental.html",
    neighborhood: "Willamsbridge",
    borough: "Bronx",
    coordinates: [40.8757718, -73.8683903],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 29,
    name: "National Dance Institute",
    description: "Have never booked here",
    url: "https://nationaldance.org/about-ndi/rentals/",
    neighborhood: "Harlem",
    borough: "Manhattan",
    coordinates: [40.8237663, -73.9397866],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 30,
    name: "New York Live Arts",
    description: "I have been meaning to book rehearsal here!",
    url: "https://newyorklivearts.org/about/rent-space/studio/",
    neighborhood: "Chelsea",
    borough: "Manhattan",
    coordinates: [40.7422303, -73.9982715],
    modeOfBooking: "Online",
    cost: "Cheap",
  },
  {
    key: 31,
    name: "Open Jar Studios",
    description: "Have not ever rehearsed here",
    url: "https://www.openjarstudios.com/studios",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.7422303, -73.9982715],
    modeOfBooking: "Phone",
    cost: "Not Cheap",
  },
  {
    key: 32,
    name: "PMT House of Dance",
    description: "Have not ever booked rehearsal here",
    url: "https://www.pmthouseofdance.com/rentals",
    neighborhood: "Flatiron",
    borough: "Manhattan",
    coordinates: [40.7433707, -73.9905081],
    modeOfBooking: "Phone",
    cost: "Cheap",
  },
  {
    key: 33,
    name: "Snug Harbor",
    description: "Have not ever rehearsed here",
    url: "https://snug-harbor.org/dancecenter",
    neighborhood: "Randall Manor",
    borough: "Staten Island",
    coordinates: [40.6433718, -74.1027431],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 34,
    name: "TOPAZ ARTS",
    description: "Have not ever rehearsed here",
    url: "http://www.topazarts.org/artist-services/",
    neighborhood: "Woodside",
    borough: "Queens",
    coordinates: [40.7486876, -73.9076964],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 35,
    name: "Brooklyn Center Stage",
    description: "Mainly a school for children I think?",
    url: "https://www.brooklyncenterstage.com/index.html",
    neighborhood: "Gowanus",
    borough: "Brooklyn",
    coordinates: [40.6694619, -73.9952143],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 36,
    name: "Kestrels",
    description: "I have not rehearsed here",
    url: "https://www.kestrels.space/rehearsal-rental",
    neighborhood: "Gowanus",
    borough: "Brooklyn",
    coordinates: [40.673488, -73.9904637],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 37,
    name: "14th Street Y",
    description: "Have not ever rehearsed here",
    url: "https://www.14streety.org/about-us/rentals/",
    neighborhood: "Union Square-ea",
    borough: "Manhattan",
    coordinates: [40.673488, -73.9904637],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 38,
    name: "La Mama",
    description: "Have yet to rehearse here.",
    url: "https://www.lamama.org/rentals/rehearsal-studios",
    neighborhood: "East Village",
    borough: "Manhattan",
    coordinates: [40.7265165, -73.9926187],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 39,
    name: "Theaterlab",
    description: "Have rehearsed here. Great space!",
    url: "https://theaterlabnyc.com/rentals/",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.7545052, -73.9946137],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 40,
    name: "A.R.T. Spaces@520",
    description: "This whole building is theatres!!!",
    url: "https://www.art-newyork.org/studio-rehearsal",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.7537593, -73.9925937],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 41,
    name: "A.R.T. Spaces @ South Oxford Space",
    description: "",
    url: "https://www.art-newyork.org/studio-rehearsal",
    neighborhood: "Ft. Greene",
    borough: "Brooklyn",
    coordinates: [40.6851473, -73.975693],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 42,
    name: "Spoke the Hub",
    description: "Never been, but seems cute!",
    url: "https://spokethehub.org/rentals/rates-policies/",
    neighborhood: "Park Slope",
    borough: "Brooklyn",
    coordinates: [40.675341, -73.97838],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 43,
    name: "University Settlement",
    description:
      "Their Multipurpose Room looks nice, and is probably good for small rehearsals",
    url: "https://www.universitysettlement.org/rentals/houston-street-center/",
    neighborhood: "Lower East Side",
    borough: "Manhattan",
    coordinates: [40.72371, -73.9925178],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 44,
    name: "Opera America",
    description: "Have not rehearsed here. They have a bunch of spaces",
    url: "https://www.operaamerica.org/national-opera-center/rooms/rehearsal-spaces-practice-rooms/",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.747773, -73.993365],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 45,
    name: "The Barrow Group",
    description: "Have not rehearsed here. They have a bunch of spaces",
    url: "https://www.barrowgroup.org/arts-center/studio-rental/",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.7545052, -73.9946137],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 46,
    name: "Chain Theatre",
    description: "Have not rehearsed here. They have a bunch of spaces",
    url: "https://www.chaintheatre.org/",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.753691, -73.993341],
    modeOfBooking: "Online",
    cost: "Not Cheap",
  },
  {
    key: 47,
    name: "Gene Frankel Theatre's Basement Rehearsal Studio",
    description: "Have not rehearsed here!",
    url: "https://www.genefrankeltheatre.com/theater-rental.html",
    neighborhood: "SoHo",
    borough: "Manhattan",
    coordinates: [40.726676, -73.9962129],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 48,
    name: "Free Mind, The Studio",
    description: "Sounds like a wonderful spot",
    url: "https://www.freemindthestudio.com/rent-the-space",
    neighborhood: "East Williamsburg",
    borough: "Brooklyn",
    coordinates: [40.7125937, -73.9357525],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 49,
    name: "Adelante Studios",
    description: "Haven't ever been here. They also sell beef?",
    url: "https://www.adelantestudios.com/availability",
    neighborhood: "K-Town",
    borough: "Manhattan",
    coordinates: [40.7473324, -73.9872803],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 50,
    name: "Tyler Brown Dance Center",
    description: "Haven't been here, but looks nice!",
    url: "https://www.tylerbrowndance.com/rentourspace",
    neighborhood: "Grammercy Park",
    borough: "Manhattan",
    coordinates: [40.7453499, -73.9886984],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 51,
    name: "Sunlight Studios",
    description: "Haven't been before!",
    url: "https://sunlightstudios.com/rental-request/",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.7592051, -73.9898251],
    modeOfBooking: "Phone",
    cost: "Not Cheap",
  },
  {
    key: 52,
    name: "New 42 Studios",
    description: "Have not been here. Big spaces",
    url: "https://www.new42studios.org/studios-the-duke-on-42nd-street/",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.7592051, -73.9898251],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 53,
    name: "SassClass Studio",
    description: "Have not been here, sounds like a fabulous organization",
    url: "https://www.sassclassnyc.com/rentals",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.750691, -73.985418],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 54,
    name: "Nancy Meehan Dance Company",
    description: "Have not rehearsed here",
    url: "https://www.nancymeehan.org/studio-rental",
    neighborhood: "West Village",
    borough: "Manhattan",
    coordinates: [40.7367406, -74.0096693],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 55,
    name: "The Ailey Studios",
    description:
      "Have not rehearsed here, but what an exciting building. It looks like they have $10 rehearsal rates for dance, so I'm marking it as cheap",
    url: "https://www.alvinailey.org/rentals-visits/rent-our-space",
    neighborhood: "Columbus Circle",
    borough: "Manhattan",
    coordinates: [40.7667683, -73.9874512],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 56,
    name: "Downtown Dance Factory",
    description: "Have not rehearsed here",
    url: "https://www.downtowndancefactory.com/about-ddf/for-pros-studio-rental/",
    neighborhood: "Tribeca",
    borough: "Manhattan",
    coordinates: [40.7114887, -74.0125731],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 57,
    name: "Paul Taylor Dance Company",
    description: "Have not rehearsed here, but it looks nice",
    url: "https://paultaylordance.org/discover/about-us/studio-rentals/",
    neighborhood: "Lower East Side",
    borough: "Manhattan",
    coordinates: [40.7114887, -74.0125731],
    modeOfBooking: "Phone",
    cost: "Not Cheap",
  },
  {
    key: 58,
    name: "Pearl Studios",
    description: "It's Pearl! We've all been there",
    url: "https://pearlstudiosnyc.com/studio-rates/",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.7114887, -74.0125731],
    modeOfBooking: "Phone",
    cost: "Not Cheap",
  },
  {
    key: 59,
    name: "Ripley-Grier 520 8th",
    description: "Such a chaotic building",
    url: "https://ripleygrier.com/",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.7114887, -74.0125731],
    modeOfBooking: "Phone",
    cost: "Not Cheap",
  },
  {
    key: 60,
    name: "Ripley-Grier W 38th",
    description: "Have not rehearsed here",
    url: "https://ripleygrier.com/",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.7550058, -73.9919843],
    modeOfBooking: "Phone",
    cost: "Not Cheap",
  },
  {
    key: 61,
    name: "Ripley-Grier 939 8th Ave",
    description: "Have not rehearsed here",
    url: "https://ripleygrier.com/",
    neighborhood: "Columbus Cirlce",
    borough: "Manhattan",
    coordinates: [40.7551091, -74.0057903],
    modeOfBooking: "Phone",
    cost: "Not Cheap",
  },
  {
    key: 62,
    name: "Ripley-Grier 131 W 72nd",
    description: "Email me if you remember what this place used to be called",
    url: "https://ripleygrier.com/",
    neighborhood: "Upper West Side",
    borough: "Manhattan",
    coordinates: [40.7551091, -74.0057903],
    modeOfBooking: "Phone",
    cost: "Not Cheap",
  },
  {
    key: 63,
    name: "Balance Arts Center",
    description: "I haven't ever been here",
    url: "https://www.balanceartscenter.space/",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.7484172, -73.992706],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 64,
    name: "AMDA Studios",
    description: "I haven't ever been here",
    url: "https://www.amdastudiorentals.com/",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.764319, -73.9834425],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 65,
    name: "Theatre Row Studios",
    description: "I haven't ever been here",
    url: "https://bfany.org/theatre-row/rehearsalstudios/",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.764319, -73.9834425],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
  {
    key: 66,
    name: "Mabou Mines",
    description: "I haven't ever been here",
    url: "https://www.maboumines.org/about/rentals/",
    neighborhood: "East Village",
    borough: "Manhattan",
    coordinates: [40.764319, -73.9834425],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 67,
    name: "Brooklyn Art Haus",
    description: "I haven't ever been here",
    url: "https://www.bkarthaus.com/studios",
    neighborhood: "Williamsburg",
    borough: "Brooklyn",
    coordinates: [40.764319, -73.9834425],
    modeOfBooking: "Online",
    cost: "Not Cheap",
  },
  {
    key: 68,
    name: "Peridance",
    description: "I haven't ever been here",
    url: "https://www.peridance.com/studio-rentals.cfm",
    neighborhood: "Union Square",
    borough: "Manhattan",
    coordinates: [40.764319, -73.9834425],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 70,
    name: "Houghton Hall Arts",
    description: "You can get a discount if you mention IndieSpace!",
    url: "https://www.houghtonhallarts.org/spacebooking",
    neighborhood: "NoMad",
    borough: "Manhattan",
    coordinates: [40.764319, -73.9834425],
    modeOfBooking: "Online",
    cost: "Not Cheap",
  },
  {
    key: 71,
    name: "Brooklyn Comedy Collective",
    description: "Very useful spaces!!",
    url: "https://www.brooklyncc.com/rentals",
    neighborhood: "Williamsburg",
    borough: "Brooklyn",
    coordinates: [40.764319, -73.9834425],
    modeOfBooking: "Online",
    cost: "Not Cheap",
  },
  {
    key: 72,
    name: "Brooklyn Ballet",
    description: "I haven't ever been here",
    url: "https://www.brooklynballet.org/about/studio-rental",
    neighborhood: "Downtown",
    borough: "Brooklyn",
    coordinates: [40.6893542, -73.9898589],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 73,
    name: "Rod Rodgers",
    description: "I haven't ever been here",
    url: "https://www.rodrodgersdance.org/studio-space",
    neighborhood: "East Village",
    borough: "Manhattan",
    coordinates: [40.764319, -73.9834425],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 74,
    name: "Iati Theater",
    description:
      "Shout-out to them for their subsized rental rates for BIPOC artists!",
    url: "https://www.iatitheater.org/rentals#book",
    neighborhood: "East Village",
    borough: "Manhattan",
    coordinates: [40.764319, -73.9834425],
    modeOfBooking: "Online",
    cost: "Not Cheap",
  },
  {
    key: 75,
    name: "Dixon Place",
    description: "I haven't ever rehearsed here",
    url: "https://dixonplace.org/rentals/",
    neighborhood: "Bowery",
    borough: "Manhattan",
    coordinates: [40.7206015, -73.9953948],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 76,
    name: "Arts On Site",
    description: "Have yet to come here!",
    url: "https://www.artsonsite.org/studios",
    neighborhood: "East Village",
    borough: "Manhattan",
    coordinates: [40.7290107, -73.9918644],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 77,
    name: "Manhattan Movement and Arts Center",
    description: "Have yet to come here!",
    url: "https://www.manhattanmovement.com/theater-and-studio-rental",
    neighborhood: "Upper West Side",
    borough: "Manhattan",
    coordinates: [40.7718087, -73.9942019],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 78,
    name: "Steps on Broadway",
    description: "What wonderful studios they look to have here",
    url: "https://www.stepsnyc.com/rentals/studio/",
    neighborhood: "Upper West Side",
    borough: "Manhattan",
    coordinates: [40.7807089, -73.9844317],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 79,
    name: "Paradise Factory",
    description: "Don't know too much about this",
    url: "http://www.paradisefactory.org/",
    neighborhood: "East Village",
    borough: "Manhattan",
    coordinates: [40.7264384, -73.9932222],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 80,
    name: "Stepping Out Studios",
    description: "This looks like a big gorgous space!",
    url: "https://www.steppingoutstudios.com/rentals",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.7639742, -74.0232205],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 81,
    name: "Emmanuel Pierre-Antoine Dance Studio",
    description: "Have not booked this space",
    url: "https://www.epadancestudionyc.com/about/studio/",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.7582154, -74.0001558],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 82,
    name: "Danznik Studios",
    description: "Three studios, one floor!",
    url: "https://www.danznik.com/studios/nyc/rentals/",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.7540345, -73.9962893],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 83,
    name: "Alden Moves Dance Theater",
    description: "Mainly seems to be an event space",
    url: "https://www.aldenmovesbk.com/space-rentals.html",
    neighborhood: "Prospect Park South",
    borough: "Brooklyn",
    coordinates: [40.6517201, -73.9769969],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 84,
    name: "Balmir",
    description: "Lots of classes. Seems more like an event space",
    url: "https://balmir.com/rental",
    neighborhood: "Flatbush",
    borough: "Brooklyn",
    coordinates: [40.647016, -73.9826532],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 85,
    name: "Brooklyn Dance Lessons",
    description:
      "Mainly booked for events, but nevertheless bookable for rehearsals!",
    url: "https://brooklyndancelessons.com/event-space-rental-brooklyn/",
    neighborhood: "Gowanus",
    borough: "Brooklyn",
    coordinates: [40.6690834, -73.9942598],
    modeOfBooking: "Online",
    cost: "Not Cheap",
  },
  {
    key: 86,
    name: "Empire Dance Studio Brooklyn",
    description: "Looks very nice!",
    url: "https://brooklyndancelessons.com/event-space-rental-brooklyn/",
    neighborhood: "Gowanus",
    borough: "Brooklyn",
    coordinates: [40.6710184, -74.0017128],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 87,
    name: "Empire Dance Studio Manhattan",
    description: "Looks fab",
    url: "https://empiredancestudio.nyc/rental-space-for-dancers-nyc/",
    neighborhood: "Midtown",
    borough: "Manhattan",
    coordinates: [40.7518436, -73.9910022],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 2,
    name: "BAX - Fifth Avenue",
    description: "Four studios and a theatre",
    url: "https://www.bax.org/space/",
    location: "Park Slope, Brooklyn",
    neighborhood: "Park Slope",
    coordinates: [40.66982, -73.9855],
    borough: "Brooklyn",
    modeOfBooking: "Online",
    cost: "Cheap",
  },
  {
    key: 88,
    name: "BAX - Hanscome Place",
    description: "It's new!",
    url: "https://www.bax.org/space/rentals/",
    neighborhood: "Downtown / Ft. Greene",
    borough: "Brooklyn",
    coordinates: [40.6852508, -73.9744064],
    modeOfBooking: "Online",
    cost: "Cheap",
  },
  {
    key: 89,
    name: "Long Island School of Ballet",
    description: "Have not ever been here",
    url: "https://licsb.com/rentals/",
    neighborhood: "Long Island City",
    borough: "Queens",
    coordinates: [40.748886, -73.9495539],
    modeOfBooking: "Email",
    cost: "Not Cheap",
  },
  {
    key: 90,
    name: "Target Margin",
    description: "Two studios, low-cost, and sometimes FREE",
    url: "https://www.targetmargin.org/",
    neighborhood: "Sunset Park",
    borough: "Brooklyn",
    coordinates: [40.647257, -74.0199579],
    modeOfBooking: "Email",
    cost: "Cheap",
  },
];

export default Spaces;

/*
    {
      "key": ,
      "name": "",
      "description": "",
      "url": "",
      "neighborhood": "",
      "borough": "",
      "coordinates": [],
      "modeOfBooking": '',
      "cost": ""
    },
*/
